### PR TITLE
Changes in main README.md

### PR DESCRIPTION
**Pull request by francovm**
This is a very small change! easy peasy

### CODE REVIEW

**Comment by francovm** [comment]
@JonoHanson Take a look when you have time

**Comment by francovm** [comment]
@JonoHanson Could you merge the pull request? I am not able to do it because I created it

**Comment by JonoHanson** [comment]
I can't merge it either, but I think @JenLowe  might need to approve again before I can

**Comment by JenLowe** [comment]
@JonoHanson Should be able to do the merge now

**Comment by JonoHanson** [comment]
I'm getting message that Merging is Block - the base branch requires all commits to be signed.

Not sure what I can do about that.

**Pull request closed without merging**
