### PR TITLE
AWS open data tutorials and GeoNet documentation

### PR DESCRIPTION
**Pull request by elidana**
Pull request to add initial documentation related to GeoNet data provided via AWS Open Data programme.

@placebojim , I am assigning you as a potential reviewer, this pull request is a placeholder that I'll discuss tomorrow with the data team.

### CODE REVIEW

**Comment by placebojim** [comment]
@elidana this PR is the one where we need to prune out the other data sets besides gnss/raw right?

**Comment by elidana** [comment]
this one too, yes. That's the one that will contain our own page to help people understanding what type of data will be found on our bucket. If CREX are not going to be included soon, I will probably just add a note here and keep the content. 
The pruning will be instead done on the AWS registry pr. 

Would be nice if you can just check you think the type of content is enough to be considered a "tutorial" to access the data. any criticism more than welcome...(THANKS!!)

**Review by placebojim — DISMISSED** [review]
This looks good to me.

**Comment by elidana** [comment]
Thanks a lot @placebojim , that's great!

and hi @JonoHanson , we need someone from the SOD team to review this and I remember you had some questions. Can you please have a look at this document , and we can chat about some of the questions you had (or just chuck them here if that's easier). Thanks!!

**Comment by elidana** [comment]
Hi @rumachan ,
sorry to drag you in but, would you mind having a look at this documentation. The idea is to describe the datasets that are going to be published on the AWS open data bucket, and this is a "tutorial" to explain content and formats used in there.

Happy to provide more context if you wish.

**Review by rumachan — CHANGES_REQUESTED** [review]
A few grammar/typos and a couple of places you might need clarification. Otherwise, all good.

line 4 is made up of
line 13 Data are in Character form for the Representation and EXchange of metereological data (CREX) format, lower case f in form and upper case E in exchange?
line 15 do you need to state the format of the QC data? Is that also CREX in some way? I see this is actually clarified on line 23
line 52 in this case Receiver INdependent EXchange format (RINEX) read well, 
line 67 a lower-case letter for hourly files with letter `[a-x]` indicating the n-th hour in the day, e.g. a for 0100, b for 0200, etc
line 75 similar to line 67
line 98 the extension is always ext?
line 138 the is duplicated
line 145 confirm site is LC or UC

**Comment by elidana** [comment]
thanks a lot @rumachan !!

very good comments, I've addressed all of them (and rebased the pr). If you're happy, can I please have your thumbsup?

**Review by rumachan — APPROVED** [review]
Looks good

**Comment by elidana** [comment]
huge thanks for your help @rumachan !!

**Pull request merged**
