### PR TITLE
new blog material

### PR DESCRIPTION
**Pull request by rumachan**
Material for further blogs.

Notebooks, data files and graphic files produced by notebooks. Blogs that had no "code" are not included. If there was a graphic file created by a notebook that was subsequently edited using a graphics program (such as libreoffice draw) then the edited graphic is also included (so a user can see what we did).

### CODE REVIEW

**Review by elidana — COMMENTED** [review]
Hi @rumachan ,

thanks for that!! It looks good. Just one question.
Are we supposed to also include the `.ipynb_checkpoints` hidden folders and content or shall we remove them from here?

**Comment by rumachan** [comment]
Well spotted. I'd checked the files in GUI file manager so didn't see hidden files. And in command line there were too many files to see.

Have removed all checkpoint files but one, which I can't remove using GitHub. If we can merge it, I'll have a go from there. Its a checkpoint on an image which is odd and probably explains why I can't remove, but I don't understand.

**Comment by elidana** [comment]
thanks @rumachan !!
in the future, you can also add an instruction to ignore these files

there is a file you can edit locally that is called .gitignore, where you can add a list of files (or file extension) to ignore and not add in git commits. I will send you some info if interested.

**Review by elidana — APPROVED** [review]
looks VERY good! thanks @rumachan !

**Pull request merged**
