### PR TITLE
_Add mamba in place of conda_

### PR DESCRIPTION
**Pull request by salichon**
mamba works better in 2022
To be worked  and  decided

### CODE REVIEW

**Comment by meganmadley** [comment]
Interesting, if we are changing this line, then do we need to change the other lines to mamba as well? e.g.

`mamba config --set channel_priority strict`
`mamba config --set channel_priority strict`
`mamba config --set auto_activate_base false`

**Comment by meganmadley** [comment]
@salichon have updated this to show how to use mamba. To test, would have to do a complete re-install, if I get the opportunity, I will give it a go with mamba but reckon this could work in the meantime?

**Review by meganmadley — APPROVED** [review]
LGTM

**Comment by AdrianBenson** [comment]
FYI mamba cannot run config commands. 

```
$> mamba config
Currently, only install, create, list, search, run, info, clean, activate and deactivate are supported through mamba.
```

**Comment by meganmadley** [comment]
Thanks @AdrianBenson for spotting this! I will modify the readme again

**Comment by meganmadley** [comment]
New PR modifying my statement https://github.com/GeoNet/data-tutorials/pull/35

**Pull request merged**
