### PR TITLE
Adding TILDE Notebooks to Data-tutorials repo and updated environment

### PR DESCRIPTION
**Pull request by meganmadley**
Adding the 3 new TILDE Data Tutorials as well as a new environment files. 
Thanks again @elidana and @mnaguit for reviewing these, I don't know if you'll need to review these again. If you'd like to see Steve and my responses to your initial comments please let me know and I can send on the file

### CODE REVIEW

**Review by mnaguit — APPROVED** [review]
Hi @megankortink . 
My feedback/comments are just suggestions.
Thanks to you & @rumachan for considering those comments.

I'll approve this PR and trust that these are already the best versions that we have.

**Review by elidana — CHANGES_REQUESTED** [review]
Hi @megankortink and @rumachan ,

thanks a lot for doing this, they look pretty good to me!
 
I have retrieved the notebooks  and they work with my local conda-jupyter installation. Out of curiosity, are the notebooks supposed to have all the cell executed already (without the use having to run them before the output is produced)?

A couple of minor comments:
- since (for now) the notebooks are focused on getting DART data, I would personally change the folder name from "TILDE" do "DART_data", also to maintain consistency with the other notebooks already existing in this repo. We can revisit this structure later on, when more data will be added to tilde (or keep the same idea as for the notebooks that are using FITS, that are still divided by data type rather than by service name)
- can you please update the table in the README.md file to also add a line about those new tutorials? 

Thanks heaps!!

**Review by elidana — APPROVED** [review]
thanks for updating those, happy for this to be merged :)

**Comment by megankortink** [comment]
Adding a comment about a discussion Elisabetta, Steve and I had in slack in regards to Elisabetta's comments:
- leave the files in a `run` state as this is the same for the other files and allows users to see what the files contain easily
- Notebook names - using `TILDE_endpoint01-dataSummary_DART.ipynb` and then for future notebooks we'd replace `DART` by `GNSS` or `FITS` or whatever. We could then provide (alomst) the same material but with a domain focus so that users would get the knowledge they need to use the API with the data domain they are familiar with.
- keep the overall folder called `TILDE`

**Pull request merged**
